### ISSUE TITLE
Improve Testing module

### ISSUE THREAD

**Issue by Gustavo-1300** [nosportugal/nos-lp-foundations#14]
### Description

The videos of Arjan are too fast, hard to search for specific topics when doing the assignment and do not explain the logic behind patching and mocking. I suggest 2 web articles which in my opinion explain better what happens when patching, mocking and using fixtures and also touch on using conftest:
- https://towardsdatascience.com/pytest-with-marking-mocking-and-fixtures-in-10-minutes-678d7ccd2f70
- https://www.tutorialspoint.com/pytest/pytest_quick_guide.htm

I also suggest this quick article which explains how to patch functions that read files, and more importantly, how to mock pandas df read function (it does it with sql query but i found it really helpful nonetheless):
- https://coderbook.com/@marcus/how-to-mock-and-unit-test-with-pandas/

**Comment by MrCordeiro** [comment]
I'm writing a PR with new testing content.

Unfortunately, the first article can't be accessed without a paid Medium account (https://towardsdatascience.com/pytest-with-marking-mocking-and-fixtures-in-10-minutes-678d7ccd2f70#ce33). Do you know if it's available elsewhere?

**Comment by Gustavo-1300** [comment]
> I'm writing a PR with new testing content.
> 
> Unfortunately, the first article can't be accessed without a paid Medium account (https://towardsdatascience.com/pytest-with-marking-mocking-and-fixtures-in-10-minutes-678d7ccd2f70#ce33). Do you know if it's available elsewhere?

No, at the time it was free to access, I tried it now and it also asked me for a paid account
